services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: zhengjiethoughts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - zjt_pgdata:/var/lib/postgresql/data

volumes:
  zjt_pgdata:
